networks:
  movie_network:
    driver: bridge

services:
  movie.db:
    image: postgres:16.0
    container_name: movie.db
    hostname: movie.db
    restart: always
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: 'UTC-4'
    command: -p 3030
    ports:
      - 3030:3030
    volumes:
      - movie-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h movie.db -p 3030 -d movie_db']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - movie_network

  movie.db.admin:
    image: dpage/pgadmin4:7.8
    container_name: movie.db.admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4040
    ports:
      - 4040:4040
    volumes:
      - movie-db-admin-data:/var/lib/pgadmin
    depends_on:
      movie.db:
        condition: service_healthy
    networks:
      - movie_network

volumes:
  movie-db-data:
  movie-db-admin-data:
